export enum SheetColumn {
  Name = "name",
  HopeLove = "love",
  HopeLearn = "learn",
  HopeLaugh = "laugh",
  HopeBecome = "become",
  HopeDoNot = "don’t",
  HopeKnow = "know",
  HopeGet = "get",
  HopeGo = "go",
  HopeGetYourMoms = "get your mom’s",
  HopeGetYourDads = "get your dad’s",
  Submitted = "submitted",
  Reviewed = "reviewed",
}
